// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```This QR code contains your ticket information for entry validation.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_uv-G7E_0xh3c4h8ZVKTmbu_Idkakkbw',
    appId: '1:189708282115:web:f0532f23463b3ee7542136',
    messagingSenderId: '189708282115',
    projectId: 'tpqms-fyp',
    authDomain: 'tpqms-fyp.firebaseapp.com',
    storageBucket: 'tpqms-fyp.appspot.com',
    measurementId: 'G-QCZJNW2N8D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBgU-SDaZM8B5D3OOcb5KITsBW05TBMXVk',
    appId: '1:189708282115:android:1a2f27abf4bc152b542136',
    messagingSenderId: '189708282115',
    projectId: 'tpqms-fyp',
    storageBucket: 'tpqms-fyp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBUA2dthk94YdilFrUIdnTNa02XtGytRlk',
    appId: '1:189708282115:ios:e3dde0a16990db20542136',
    messagingSenderId: '189708282115',
    projectId: 'tpqms-fyp',
    storageBucket: 'tpqms-fyp.appspot.com',
    iosBundleId: 'com.example.tpqms',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBUA2dthk94YdilFrUIdnTNa02XtGytRlk',
    appId: '1:189708282115:ios:e3dde0a16990db20542136',
    messagingSenderId: '189708282115',
    projectId: 'tpqms-fyp',
    storageBucket: 'tpqms-fyp.appspot.com',
    iosBundleId: 'com.example.tpqms',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB_uv-G7E_0xh3c4h8ZVKTmbu_Idkakkbw',
    appId: '1:189708282115:web:5a68beb962f4b585542136',
    messagingSenderId: '189708282115',
    projectId: 'tpqms-fyp',
    authDomain: 'tpqms-fyp.firebaseapp.com',
    storageBucket: 'tpqms-fyp.appspot.com',
    measurementId: 'G-6NJ1TVRKPX',
  );
}
